# fly.toml app configuration file generated for full-stack-open-pokedex-cool-breeze-8404 on 2025-03-13T21:06:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-cool-breeze-8404'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3001  
  force_https = true  
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0  
  processes = ['app']

   [[http_service.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false
    grace_period = "5s"   

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "3001"  

[deploy]
  strategy = "canary"  

