app = 'full-stack-open-pokedex-black-shape-1529'
primary_region = 'ams'

[build]

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "5s"

[deploy]
  strategy = "canary"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
